name: Release PHAR

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      -
        name: List keys
        run: gpg -K

      -
        name: Sign the PHAR
        # if: github.event_name == 'release'
        run: |
          gpg --local-user maks.rafalko@gmail.com \
              --yes \
              --passphrase="${{ secrets.GPG_PASSPHRASE }}" \
              --detach-sign \
              --output src/SomeClass.php.asc \
              src/SomeClass.php

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/SomeClass.php*
          file_glob: true
          tag: ${{ github.ref }}
